.TH setprofile 1 "May 3, 2017" "Set siddio-homecontrol profile"
.SH NAME
setprofile
\- Set siddio-homecontrol profile

.SH SYNOPSIS
setprofile [options]

.br
setprofile profilename

.SH DESCRIPTION
setprofile is a minimal shell client for siddio-homecontrol.

.BR
\fBsetprofile\fP is released under the GNU General Public License version 3.

.SH OPTIONS
.SS
.SS Options:

.TP
.B \-\-list
Lists all the configured profiles

.SH "SEE ALSO"
.BR setprofile.conf(5)

.SH WEB
.BR http://ltworf.github.io/siddio/

.SH AUTHORS
.nf
Salvo "LtWorf" Tomaselli <tiposchi@tiscali.it>
.br
