#!/bin/sh
set -e

if test -z "$HOST$PORT"; then
    if test -f "~/.config/setprofile.conf"; then
        . ~/.config/setprofile.conf
    fi
    . /etc/siddio/setprofile.conf
fi

if test -z "$1" || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "    Usage:"
    echo $0 --list
    echo $0 profilename [profilename ...]
    exit 0
fi

while test -n "$1"; do
    if test "$1" = "--status"; then
        printf "s$2" | nc $HOST $PORT
        echo
        exit 0
    elif test "$1" = "--list"; then
        printf l | nc $HOST $PORT
        echo
        exit 0
    fi
    printf a$1 | nc $HOST $PORT
    shift
done
