.TH setprofile 5 "May 3, 2017" "Set siddio-homecontrol profile"

.SH NAME
.B setprofile.conf
\- configuration file for the setprofile command

.SH SYNOPSIS
/etc/siddio/setprofile.conf
.br
~/.config/setprofile.conf

.SH DESCRIPTION
setprofile is a minimal shell client for siddio-homecontrol.

.BR
\fBsetprofile\fP is released under the GNU General Public License version 3.

.SH OPTIONS
This file is sourced by a shell script.
.SS

.TP
.B HOST
The hostname or IP address to connect to the homecontrol server

.TP
.B PORT
The port to connect to the homecontrol server

.SH "SEE ALSO"
.BR setprofile (1)

.SH WEB
.BR http://ltworf.github.io/siddio/

.SH AUTHORS
.nf
Salvo "LtWorf" Tomaselli <tiposchi@tiscali.it>
.br
